In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("1_txn_data.csv")

In [3]:
df

,adv_id,value_in_paise,payment_gateway,payment_method,payment_status,created_at,app_id,from_currency_amount,from_currency,to_currency_amount,to_currency,transaction_fee_amount,transaction_fee_currency
0,NaN,3000,RAZORPAY,UPI,PROCESSED,2024-10-18 09:34:14.247708+00:00,sikka,300.0,sikka,30.0,INR,130.0,paise
1,2d3ad81b-a068-460a-9f35-60d7df3c2b78,3000,RAZORPAY,UPI,PROCESSED,2024-10-18 09:34:14.247708+00:00,sikka,300.0,sikka,30.0,INR,130.0,paise
2,3052eb57-f48d-4bb5-9469-bf4e1c71c8a9,3000,RAZORPAY,UPI,PROCESSED,2024-10-18 09:34:14.247708+00:00,sikka,300.0,sikka,30.0,INR,130.0,paise
3,802684aa-0870-4258-9561-aa84f6aa88d8,3000,RAZORPAY,UPI,PROCESSED,2024-10-18 09:34:14.247708+00:00,sikka,300.0,sikka,30.0,INR,130.0,paise
4,92edbd60-5179-47ca-bb6d-122a157a27e0,3000,RAZORPAY,UPI,PROCESSED,2024-10-18 09:34:14.247708+00:00,sikka,300.0,sikka,30.0,INR,130.0,paise
...,...,...,...,...,...,...,...,...,...,...,...,...,...
65931,a7202c1e-a824-4110-9299-70337e70d7e8,5000,RAZORPAY,UPI,PROCESSED,2024-10-22 18:05:59.258948+00:00,bharat_cash_incent,5000.0,bharat_coin,50.0,INR,130.0,paise
65932,a7202c1e-a824-4110-9299-70337e70d7e8,5000,RAZORPAY,UPI,PROCESSED,2024-10-23 01:40:47.789158+00:00,bharat_cash_incent,5000.0,bharat_coin,50.0,INR,130.0,paise
65933,5f1df8ee-28f1-429a-86b1-8a1c353f8517,5000,RAZORPAY,UPI,PROCESSED,2024-10-23 02:30:45.362964+00:00,bharat_cash_incent,5000.0,bharat_coin,50.0,INR,130.0,paise
65934,06447f6b-a70f-4a5c-8ab4-e284610e9080,500,RAZORPAY,UPI,PROCESSED,2024-10-21 11:33:32.880973+00:00,bharat_cash_incent,500.0,bharat_coin,5.0,INR,130.0,paise
65935,4d4b336d-ddff-4371-b967-0f1beaa15a9c,500,RAZORPAY,UPI,PROCESSED,2024-10-19 09:20:09.314955+00:00,bharat_cash_incent,500.0,bharat_coin,5.0,INR,130.0,paise

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65936 entries, 0 to 65935
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   adv_id                    65914 non-null  object
 1   value_in_paise            65936 non-null  int64
 2   payment_gateway           65936 non-null  object
 3   payment_method            65936 non-null  object
 4   payment_status            65936 non-null  object
 5   created_at                65936 non-null  object
 6   app_id                    65936 non-null  object
 7   from_currency_amount      65936 non-null  float64
 8   from_currency             65936 non-null  object
 9   to_currency_amount        65936 non-null  float64
 10  to_currency               65936 non-null  object
 11  transaction_fee_amount    65936 non-null  float64
 12  transaction_fee_currency  58450 non-null  object
dtypes: float64(3), int64(1), object(9)
memory usage: 6.5+ MB

In [5]:
df=df.dropna(subset=['adv_id'])

In [6]:
df

,adv_id,value_in_paise,payment_gateway,payment_method,payment_status,created_at,app_id,from_currency_amount,from_currency,to_currency_amount,to_currency,transaction_fee_amount,transaction_fee_currency
1,2d3ad81b-a068-460a-9f35-60d7df3c2b78,3000,RAZORPAY,UPI,PROCESSED,2024-10-18 09:34:14.247708+00:00,sikka,300.0,sikka,30.0,INR,130.0,paise
2,3052eb57-f48d-4bb5-9469-bf4e1c71c8a9,3000,RAZORPAY,UPI,PROCESSED,2024-10-18 09:34:14.247708+00:00,sikka,300.0,sikka,30.0,INR,130.0,paise
3,802684aa-0870-4258-9561-aa84f6aa88d8,3000,RAZORPAY,UPI,PROCESSED,2024-10-18 09:34:14.247708+00:00,sikka,300.0,sikka,30.0,INR,130.0,paise
4,92edbd60-5179-47ca-bb6d-122a157a27e0,3000,RAZORPAY,UPI,PROCESSED,2024-10-18 09:34:14.247708+00:00,sikka,300.0,sikka,30.0,INR,130.0,paise
5,c512389d-a713-4642-bd0e-7eb56490fd26,3000,RAZORPAY,UPI,PROCESSED,2024-10-18 09:34:14.247708+00:00,sikka,300.0,sikka,30.0,INR,130.0,paise
...,...,...,...,...,...,...,...,...,...,...,...,...,...
65931,a7202c1e-a824-4110-9299-70337e70d7e8,5000,RAZORPAY,UPI,PROCESSED,2024-10-22 18:05:59.258948+00:00,bharat_cash_incent,5000.0,bharat_coin,50.0,INR,130.0,paise
65932,a7202c1e-a824-4110-9299-70337e70d7e8,5000,RAZORPAY,UPI,PROCESSED,2024-10-23 01:40:47.789158+00:00,bharat_cash_incent,5000.0,bharat_coin,50.0,INR,130.0,paise
65933,5f1df8ee-28f1-429a-86b1-8a1c353f8517,5000,RAZORPAY,UPI,PROCESSED,2024-10-23 02:30:45.362964+00:00,bharat_cash_incent,5000.0,bharat_coin,50.0,INR,130.0,paise
65934,06447f6b-a70f-4a5c-8ab4-e284610e9080,500,RAZORPAY,UPI,PROCESSED,2024-10-21 11:33:32.880973+00:00,bharat_cash_incent,500.0,bharat_coin,5.0,INR,130.0,paise
65935,4d4b336d-ddff-4371-b967-0f1beaa15a9c,500,RAZORPAY,UPI,PROCESSED,2024-10-19 09:20:09.314955+00:00,bharat_cash_incent,500.0,bharat_coin,5.0,INR,130.0,paise

In [7]:
df['created_at']=pd.to_datetime(df['created_at'])

C:\Users\mahad\AppData\Local\Temp\ipykernel_10732\75437180.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['created_at']=pd.to_datetime(df['created_at'])

In [10]:
df=df.sort_values(by=['adv_id','created_at'])
df

,adv_id,value_in_paise,payment_gateway,payment_method,payment_status,created_at,app_id,from_currency_amount,from_currency,to_currency_amount,to_currency,transaction_fee_amount,transaction_fee_currency
37176,0000-0000,500,RAZORPAY,UPI,PROCESSED,2024-10-16 07:58:20.279989+00:00,bharat_cash_incent,500.0,bharat_coin,5.0,INR,130.0,paise
16497,0000-0000,3000,RAZORPAY,UPI,PROCESSED,2024-10-17 02:13:03.216271+00:00,money_hi,300.0,mhcoin,30.0,INR,130.0,paise
18986,0000-0000,3000,RAZORPAY,UPI,PROCESSED,2024-10-17 02:13:03.216271+00:00,money_hi,300.0,mhcoin,30.0,INR,130.0,paise
19230,0000-0000,3000,RAZORPAY,UPI,PROCESSED,2024-10-17 02:13:03.216271+00:00,money_hi,300.0,mhcoin,30.0,INR,130.0,paise
22424,0000-0000,3000,RAZORPAY,UPI,PROCESSED,2024-10-17 02:13:03.216271+00:00,money_hi,300.0,mhcoin,30.0,INR,130.0,paise
...,...,...,...,...,...,...,...,...,...,...,...,...,...
41127,fffbdc78-8b44-496a-94ce-b60968c77614,500,RAZORPAY,UPI,FAILED,2024-10-18 02:51:35.281609+00:00,rupiyo,5.0,rupiyo_token,5.0,INR,130.0,paise
41126,fffbdc78-8b44-496a-94ce-b60968c77614,500,RAZORPAY,UPI,PROCESSED,2024-10-18 03:32:07.958417+00:00,rupiyo,5.0,rupiyo_token,5.0,INR,130.0,paise
38232,fffd0ef6-9453-4f5a-a316-666799643e68,3000,RAZORPAY,UPI,PROCESSED,2024-10-21 17:28:55.917413+00:00,in_cash,300.0,iccoin,30.0,INR,130.0,paise
44222,fffe06a5-7891-4189-9292-e5bb7f14715e,5000,RAZORPAY,UPI,PROCESSED,2024-10-17 04:48:08.866934+00:00,bharat_cash_incent,5000.0,bharat_coin,50.0,INR,130.0,paise
59628,ffff1a0f-f2ba-4646-909d-033851ad4ff5,500,RAZORPAY,UPI,PROCESSED,2024-10-22 05:36:28.611302+00:00,bharat_cash_incent,500.0,bharat_coin,5.0,INR,130.0,paise

In [11]:
df_group=df.groupby('adv_id')

# 1.How long did it take for the user to make their second transaction on average?

In [12]:
def time_to_second_txn(group):
    if len(group) >= 2:
        delta = group.iloc[1]['created_at'] - group.iloc[0]['created_at']
        return delta.total_seconds() / 3600  
    return None

In [13]:
second_txn_times = df_group.apply(time_to_second_txn).dropna()
avg_hours_to_second_txn = second_txn_times.mean()

In [14]:
print("Average time to second transaction (in hours):", round(avg_hours_to_second_txn, 2))

Average time to second transaction (in hours): 28.38

# 2.How many percent of users who did the first transaction also did the second transaction?

In [15]:
users_with_txns = df_group.size()
users_with_second_txn = users_with_txns[users_with_txns >= 2].count()
percent_with_second_txn = (users_with_second_txn / users_with_txns.count()) * 100

In [16]:
print("Percentage of users who made a second transaction:", round(percent_with_second_txn, 2), "%")

Percentage of users who made a second transaction: 29.83 %

# 3. What was the average transaction amount after the first transaction?
# For example, if a userâ€™s first transaction was 100 INR and they subsequently made
# transactions of 50, 100, and 200 INR, the average would be (50 + 100 + 200) / 3.

In [18]:
def avg_amount_after_first(group):
    if len(group) >= 2:
        return group.iloc[1:]['value_in_paise'].mean() / 100  #It is converting paise to INR
    return None

In [20]:
avg_amounts = df_group.apply(avg_amount_after_first).dropna()
avg_txn_amt_after_first = avg_amounts.mean()

In [21]:
print("Average transaction amount after the first (in INR): â‚¹", round(avg_txn_amt_after_first, 2))

Average transaction amount after the first (in INR): â‚¹ 28.05

# Assumptions Made:
Only transactions with a valid adv_id (user ID) are analyzed.

All transaction statuses (e.g., PROCESSED, FAILED) are included unless stated otherwise.

The time to the second transaction is calculated as the time difference between the first and second transactions sorted by timestamp, measured in hours.

Users with at least one transaction are considered, and the percentage is based on how many of them made a second transaction.

The average amount after the first transaction includes all subsequent transactions and is converted from paise to INR.